### ISSUE TITLE
implement serverctrl.restart

### ISSUE THREAD

**Issue by SailReal** [bb30/learn-duel-web#14]

**Comment by DonatJR** [comment]
this should probably be an issue on the normal learn-duel repo?

**Comment by SailReal** [comment]
Think it should be in both repos. 
In learn-duel we have to implement `serverctrl.restart` and in `learn-duel-web` we use this so we should have maybe two issues?

**Comment by DonatJR** [comment]
okay sure, but in this repo it would just be one call. it already exists here so let's just keep it
