### ISSUE TITLE
Implement game input to user mapping

### ISSUE THREAD

**Issue by SailReal** [bb30/learn-duel-web#18]

**Comment by SailReal** [comment]
Hmm, right now I have no idea how we could implement the user mapping with the answer buttons. the user  don't have an (incremental) number which we could use to calculate the answer number but without...maybe we should implement that or do you have a better idea?

**Comment by DonatJR** [comment]
I just used the numbers from the number keys (1-4 and 6-9) in the offline version of the game for now. As we already discussed, local multiplayer is more than likely to get cut once online functionality is implemented so I wouldn't spend too much time and effort implementing a clean solution for this right now.

6-9 will automatically get mapped to the second player by the controller (if one is added to game)
