### ISSUE TITLE
Create a page using Polymer (help page)

### ISSUE THREAD

**Issue by SailReal** [bb30/learn-duel-web#24]
On a different branch, maybe https://github.com/SailReal/learn-duel-web/tree/polymer

**Comment by DonatJR** [comment]
@SailReal I created a help page in https://github.com/SailReal/learn-duel-web/commit/4afa295bc978019f0df2df21abe04fdb49a07357 but the styling does not work with our webpack scoped styles (polymer uses a relatively new feature called `shadow-dom` which they use to scope css on their own. they use style-templates for this, which are like normal polymer templates but contain only styling).

It's probably not worth our time to investigate this issue further right now, what do you think?

**Comment by SailReal** [comment]
> It's probably not worth our time to investigate this issue further right now, what do you think?

We actually use Vue.js so yes we played around with polymer, integrated a site, I didn't look at it but if it is not perfectly styled, don't care about... we're using vue!
