### ISSUE TITLE
Implement akka http

### ISSUE THREAD

**Issue by SailReal** [bb30/learn-duel-web#48]

**Comment by SpurNut** [comment]
- use API from LearnDuelWeb as start point and cerate a enhanced one for REST-calls
- implement AKKA server with all dependencies
- implement the REST-API using AKKA in a new view e.g. WebController.scala
- implement tests for the REST-calls

**Comment by SailReal** [comment]
Created this issue in [LearnDuel](https://github.com/bb30/learn-duel/issues/10)
